90000 Start of FLOWTUBE  Ruben+++++++++++++++++++++++++++++++++
90002 Invalid number of #1a#
90004 Invalid distance of #1a#
90005 Invalid depth of borehole
90007 Overlapping borehole diameter in #1a#
90008 Heat exchanger tube (dht) is greater than borehole diameter (dbh)
90011 Warning invalid number for heat exchanger(#4i2#,#5i2#) use 0=off; 1=on
90013 Warning active borehole outside calculation frame (#1a#)
90014 or switch heat exchanger (#4i2#,#5i2#) to off
90020 Invalid value of heatconductivity #1a#
90021 Invalid value of heatcapacity #1a#
90022 Invalid value of density #1a#
90023 Invalid value of phasecon; use 0-365 days
90024 Phasecon exceeds max value auto-reduce to #4i3# day(s)
90027 Invalid value of soil-water-ratio #1a# use range 0.0-1.0; 0=soil; 1=water
90030 Invalid value of serial-parallel-ratio #1a# use 0.0=serial; 1.0=parallel
90031 Invalid number of horizon(s) use range 1-#4i3#
90033 Horizon #1a# is outside calculation matrix
90034 Horizon sequence mismatch (permitted sequence: 1=high; 2=middle; 3=low)
90035 Thickness of horizon(#1a#) exceeds number of levels nol=#4i3#
90036 Max value of thickness (#1a#) is #4i3#
90037 Valid range of thickness(#1a#): #4i3#<thicknz(#1a#)<#5i3#
90040 Horizon(#1a#) overlapps horizon(#2a#)
90041 Horizon(#1a#) overlapps horizon(#2a# & #3a#)
90042 Climate mismatch use range (0-14)
90100 Division by zero in #2a# by #1a# execution terminated in loop #1f4.0#
90105 Imaginary root in #2a# by #1a# execution terminated in loop #1f4.0#
90110 Undefined argument of log-function in #2a# by #1a# in loop #1f4.0#
90115 Temperatur out of range in #2a# by #1a# in loop #1f4.0#
90901 End of FLOWTUBE  Ruben++++++++++++++++++++++++++++++++++++
